# Research involving Vessels {-}

To conduct research involving a vessel in the Bahamas, in addtion to permits, you will also need two additiona forms of permission

1. A Port Access Pass to birth in the Bahamas
2. For Research in National Parks you will need to pay marine fees through the Bahamas National Trust

## Port Authority Access Pass {-#port-authority-access-pass}

Permission to birth a vessel in the Bahamas is provided by the Port Authority through an Access Pass. 

Details of how to obtain an access pass are provided [here][(https://www.bahamas.gov.bs/wps/portal/public/gov/government/services/application%20for%20access%20passes/!ut/p/b1/vVbZspvIEvwWf4CsbnYe2fcGsWl5IYSQ2IVYJJavH869npg5dvg4JsLH1BMRVWRnZlVT29P2sD3dz688PQ95cz9Xb-8nKsKBYnEcwVgKCSigBY7JObSKMQhu99uDelx4obdSSXKjKXjaTQ0QpliRRtdSckiQGcRydSCjhy-OZCGNp-JCV4OqYNhsvvYN0-sxf_JGzL_FQg9U2-uySKJ1q8bKQSc891wpU5IGhAwl5MqF9VKm0eqUso9GJJHlwCFTTAdk0e0pYQxPfOFPtnuKTAkckNnxfGcvTp6KyWH88mUldFwJgZ88HHjPl5EpbuWLyzhpcLiyg9_qfyKITYCP9LIh-X39jwD_rf7HhF_4pW9PeVx_HS_1V_AVZ1magSRDMJDBIGRWN08fHuCN3_8SPhLwwy8Y2Pa4JtD_SvBDADQIONeDO8DQ9NbfHgARecX80JZycQswA088T4OUz1ACmBd0IfJlzUs86IknC5YAeqBfvM4efWnQB-Q7SegGPMcNauV13wPamM-ugAKkjIAEnoJ_NqBC2swqAe07HImtGlF_GpB8AyyOFCs22qhI4Y3fJQptJc7ZLWO-NzipDxpTwmQfOIIPdFd6RNe2tUxAY-RI12po7M6DMR9ZQdUzLiOqgWOzyJfyatqJgN9dj8RSBxERW1d1GYKk2ABzgNdb2ryMy2wojWtLh6c7TlmjyreWD5fLLvWMyiMqMtd609jjzUQ--wlTlWN8zpBforPeNXb9VHM6tjI23mc8aItDRBNxEl3lTQaRqJ_vWPEKNVITcfxKU9rivqxr2dt_C6LY1k54s9zn3yzHVZWjTNyW4Gc58DPA399j7waZJCBJshBjKYzGaEhvw9VtWuh1TpLCSL9gwam9YgJhhCY05VU43e2M0cRPKoooNp8ruTdbNWAnOjxfnz0ojlxq1nelZzG1A_JdmKb8wEkOkGxd2b04TSwGQrehyvLTyVWv4vQyoyFMN40HYjVzH0WbOfdQBvkDujIqZ_2Fz_T1dbiVzCQKhaOCDDGyqFUq4bhHitdQW25Ka4zpK3lN_I2yOM6Ko9T8RtG3SG3q6y_uDfSjp8sOR4WuW7GurXICL3j5KCgXxCbIl1oIJWj4orZ4hYb5EkQoEb9JLM4wl4-_uDcA8dmA78dYseGfBsT_qKSKY4NPZ_iuaYjd7_fw3VwyLAVJmiFYhgIEwfx_Llmx10ZJQ7fH5YlY0Vg0zz3mNZ8aMtzVGWk8nPFhn7qZLd3quOdTpk7o3lTVGjvb-4lLvbwelBDr0tSebLtfcr0QeMXwTKcMhePOuPflIuZ9X4iYBqJqxHF2loxTy1T-o21LMutKalji281QS9FOlE17fxSC8Wo1OrthjFH4Veu9QlvU6qq7NZculF39Wc5ipcx4VkQCKiKl1Oj1VHjcVvM5XRerj6fT_dFZMBm-REyoTAEIILJ8NUBBPXtIRn0hzEAMoO97Uy9NyOvQejHGfwud9ZsI_Go6yc8G_O4nK-B_GND7_ZK-Xw4ZyGIsABRJUZAlmLV3A2JaF_1RcgZDbjYo3tD7147VetIzL7OkYPiN6O4HakN23tPdSVKma8zDjuj9aU6eQjr4saIfN3xPWMWD0uyHY7ZHKRSvY0kK8mzlrzupjfRSEo6FRXhnE3lyppSnZYR865NFI1OS6mkPvvO1U5ITYpZRTWOnRnuPaFAX7n5_x1pGCxkn2MQq2PeKsb-B_uz0j6pZl121fznnzQFNDudxxJfto34ZhmGSunRD_w7ivPkn4uXwLbi_ADDrYws!/dl4/d5/L2dBISEvZ0FBIS9nQSEh/): 

Please visit the above website for the latest details. If the guidance below differs from that on the above government website, the information on the government website is the official guidance and should be used in preference to the below. At the time of writing in October 2020 the information is as follows: 

__Application for Access Passes__

The Port Department issues Port Approved Passes to ships wanting to berth in the Bahamas Port.  


__Eligibility__

Any ship wanting to berth in a Bahamas Port.

Process 
The ship interested in berthing in a Bahamian Port, must submit a request in writing to the Port Department requesting permission to birth.  
This request must include the schedules dates, routes, schematics, personnel, and security plan.

The request will be reviewed, and once deemed acceptable, the port will issue pre-approved passes to the captain of the ship for all of the ship’s crew and passengers.  

Passengers on the ships are advised to provide additional photo identification to go along with port approved pass.

__Application Form(s)__ 
No form is needed for this service.

__Supporting Documents__ 
Schedules dates
Routes
Schematics
Personnel listing
Security Details

__Ferryboat and Jet Ski operators__ must also provide:

Operators Licence
Master’s Licence and/or STCW Certification  
Turn-around time 
Access passes are processed within 1 to 5 working days.
Deadline 
There is no deadline associated with this service.
Related Fee(s) 
There is no associated fee for this service.

For more information please contact 
Any of the offices listed below, 9:00 am to 5:00 pm, Monday to Friday, except public holidays.

New Providence Offices

Prince George Wharf
P.O. Box N-8175
Nassau, New Providence
The Bahamas
Tel. (242) 322-1596 or 326-7654
Fax. (242) 322-5545

Dock Master’s Office
Potter’s Cay
Nassau, New Providence
The Bahamas
Tel. (242) 393-1064
Fax. (242) 394-1240

Grand Bahama Office
P.O. Box F 2044
Freeport, Grand Bahama
The Bahamas
Tel. (242) 352-9163
Fax. (242) 351-4538

Abaco Office
P.O. Box Ab 20922
Marsh Harbour, Abaco
The Bahamas
Tel. (242) 367-0038
Fax. (242) 367-0041

## Marine Fees at the Bahamas National Trust {-#marine-fees at-the-bahamas-national-trust}

For research in national parks in the Bahamas you will need to pay the relevant marine fees through the Bahamas National Trust. 

For more information visit the [Marine Fees](https://bnt.bs/payexumapark/) section at the Bahamas National Trust. Additional Research Fees are also payable to the BNT and can be accessed at the bottom of the [Marine Fees](https://bnt.bs/payexumapark/) page. 